### ISSUE TITLE
[BUG] Item Description

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-pf2e-encounter-aftermath#12]
Descriptions no longer show on mouseover.

### Current

https://github.com/ironmonk88/monks-pf2e-encounter-aftermath/assets/99844555/86beab0c-9ee8-4509-a87e-63fe34449516

### Expected

![Aftermath_Tab](https://github.com/ironmonk88/monks-pf2e-encounter-aftermath/assets/99844555/ec2be263-3533-4d60-a0a7-9f4c61984ab7)

Foundry 11.315
PF2 5.13.6
Aftermath 11.05

**Comment by ironmonk108** [comment]
Fixed in the latest version
