### ISSUE TITLE
[Feature Request] Output summary to chat

### ISSUE THREAD

**Issue by S-North** [ironmonk88/monks-pf2e-encounter-aftermath#13]
Just started using this mod and am loving it.
Was thinking that an option to output a summary of the characters actions to the chat log would be good. When the advance button
is activated it could just include what action each character was taking. Just for everyones reference, but for my forgetful GM brain in particular.
Would also be cool if a whisper with any macros to run could be sent to individual players chat to resolve the actions.

**Comment by ironmonk108** [comment]
Added to the latest version.
