### ISSUE TITLE
[BUG] Untranslated key shown in Aftermath tab of party window

### ISSUE THREAD

**Issue by farling42** [ironmonk88/monks-pf2e-encounter-aftermath#21]
**Describe the bug**
Untranslated key shown in Aftermath tab of party window

**To Reproduce**
1. Open Party sheet
2. Switch to Aftermath tab
3. See wrong strings on display
 
**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/44c497e6-eb74-467b-a1e4-1a55d04cb0ae)

**Please complete as much of the following information as possible:**
 - Browser: Chrome 130.0.6723.70
 - Foundry Version: 12.331
 - System: PF2e 6.5.1
 - Module version: 12.01

**Additional context**

**Comment by ironmonk108** [comment]
Fixed in the latest version
